alias sgpu0="export CUDA_VISIBLE_DEVICES=0"
alias sgpu1="export CUDA_VISIBLE_DEVICES=1"
alias sgpu2="export CUDA_VISIBLE_DEVICES=2"
alias sgpu3="export CUDA_VISIBLE_DEVICES=3"
alias sgpu4="export CUDA_VISIBLE_DEVICES=4"
alias sgpu5="export CUDA_VISIBLE_DEVICES=5"
alias sgpu6="export CUDA_VISIBLE_DEVICES=6"
alias sgpu7="export CUDA_VISIBLE_DEVICES=7"

alias gs="git status"
alias gl="git log"
alias gr="git reset"
alias gm="git commit"
alias ga="git add"
alias gb="git branch"
alias gc="git checkout"
alias gd="git diff"
alias glp="git log --pretty=\"%h %cd %an ==>%s\" --date=short"
alias ll="ls -l --color"
